language: node_js

services:
  - mongodb

node_js:
  - "0.11"

env:
  global:
    secure: ofjLYJe/IFFvK3jV6RskdPWOeR+bZvXb0pk+e/wH3jjnClq6+Fy+5ZUx2z/tsCHYyx8TWaaPTRsTv+akw2DpBL3l/GsmNVAPw/0ULiHzQ/yNwEnMYmaqoPZVE43Svh+AlCN93sWw3W+f1xjVq4ZeTgqjGYM73EwmMTsMzfU7yJA=

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f81931d2ca2fde2e1a8
    on_success: change
    on_failure: always
    on_start: false