language: node_js

node_js:
  - "0.11"

env:
  global:
    secure: ofjLYJe/IFFvK3jV6RskdPWOeR+bZvXb0pk+e/wH3jjnClq6+Fy+5ZUx2z/tsCHYyx8TWaaPTRsTv+akw2DpBL3l/GsmNVAPw/0ULiHzQ/yNwEnMYmaqoPZVE43Svh+AlCN93sWw3W+f1xjVq4ZeTgqjGYM73EwmMTsMzfU7yJA=