language: node_js

node_js:
  - "0.11"

env:
  global:
    - secure: ZMSoUUDPlsvxOxlzK/QCgnbezxc8DHenbPhYz2ogh9H9u6JA9fW2HW2Hxq+eMeBmjyZiB+4S2MbK6NYoQVQOy1Ek2+ARs/PYNnKDLP0Mat1+l/maatvFOdt+m/bfsbVGDcW+UZE4gXRiAXJmNJitpyjSk1iWT/PS6buCuCcaOC0=
